# Generated by Django 4.0.6 on 2022-07-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        ('questions', '0004_alter_mcquestion_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kataquestion',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='squestion',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment'),
        ),
    ]
