# Generated by Django 4.0.6 on 2022-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_kataquestion_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squestion',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
