# Generated by Django 4.0.6 on 2022-07-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_squestion_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kataquestion',
            old_name='text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='katatest',
            old_name='text',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='mcanswer',
            old_name='text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='squestion',
            old_name='text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='kataquestion',
            name='starter_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
