# Generated by Django 4.0.6 on 2022-07-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_text_kataquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kataquestion',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
