# Generated by Django 4.0.6 on 2022-07-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        ('questions', '0008_alter_kataquestion_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kataquestion',
            name='assessment',
        ),
        migrations.AddField(
            model_name='kataquestion',
            name='assessment',
            field=models.ManyToManyField(blank=True, null=True, to='assessment.assessment'),
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='assessment',
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='assessment',
            field=models.ManyToManyField(blank=True, null=True, to='assessment.assessment'),
        ),
        migrations.RemoveField(
            model_name='squestion',
            name='assessment',
        ),
        migrations.AddField(
            model_name='squestion',
            name='assessment',
            field=models.ManyToManyField(blank=True, null=True, to='assessment.assessment'),
        ),
    ]
