# Generated by Django 4.0.6 on 2022-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        ('questions', '0009_remove_kataquestion_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kataquestion',
            name='assessment',
            field=models.ManyToManyField(blank=True, to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='assessment',
            field=models.ManyToManyField(blank=True, to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='squestion',
            name='assessment',
            field=models.ManyToManyField(blank=True, to='assessment.assessment'),
        ),
    ]
