# Generated by Django 4.0.6 on 2022-07-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_kataquestion_assessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcquestion',
            old_name='text',
            new_name='question',
        ),
    ]
