# Generated by Django 4.0.6 on 2022-07-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_rename_text_mcquestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.squestion')),
            ],
        ),
    ]
