# Generated by Django 4.0.5 on 2022-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='duration of assessment in minutes'),
        ),
    ]
