# Generated by Django 4.0.5 on 2022-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='pass_mark',
            field=models.PositiveIntegerField(help_text='score in %'),
        ),
    ]
