# Generated by Django 4.0.5 on 2022-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_assessment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='category',
            field=models.CharField(choices=[('multiple_choice', 'multiple_choice'), ('kata', 'kata'), ('subjective', 'subjective')], max_length=20, null=True),
        ),
    ]
