# Generated by Django 4.0.5 on 2022-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_alter_assessment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='pass_mark',
            field=models.PositiveIntegerField(help_text='Pass Score in %'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='Duration of assessment in minutes'),
        ),
    ]
