# Generated by Django 4.0.5 on 2022-07-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_assessment_pass_mark_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='MCAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='MCQuestion',
        ),
    ]
