# Generated by Django 4.0.5 on 2022-07-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_katafeedback_mcfeedback_sfeedback_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kataquestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='katatest',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mcanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mcfeedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mcfeedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='sfeedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sfeedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='squestion',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='KataFeedback',
        ),
        migrations.DeleteModel(
            name='KataQuestion',
        ),
        migrations.DeleteModel(
            name='KataTest',
        ),
        migrations.DeleteModel(
            name='MCAnswer',
        ),
        migrations.DeleteModel(
            name='MCFeedback',
        ),
        migrations.DeleteModel(
            name='MCQuestion',
        ),
        migrations.DeleteModel(
            name='SFeedback',
        ),
        migrations.DeleteModel(
            name='SQuestion',
        ),
    ]
