# Generated by Django 4.0.5 on 2022-07-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_remove_kataquestion_assessment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'Student Grades'},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name_plural': 'All Invites'},
        ),
    ]
