# Generated by Django 4.0.5 on 2022-07-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcanswer',
            options={'verbose_name_plural': 'Multiple Choice Answers'},
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AlterModelOptions(
            name='squestion',
            options={'verbose_name_plural': 'Subjective Questions'},
        ),
    ]
