# Generated by Django 4.0.6 on 2022-07-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_mcanswer_options_alter_mcquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katatest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katatests', to='questions.kataquestion'),
        ),
    ]
