# Generated by Django 4.0.6 on 2022-07-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_katatest_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katatest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.kataquestion'),
        ),
    ]
