# Generated by Django 4.0.6 on 2022-07-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_katatest_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katatest',
            name='text',
            field=models.CharField(help_text='Create a test for this kata', max_length=5000),
        ),
    ]
