# Generated by Django 4.0.6 on 2022-07-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_katatest_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katatest',
            name='text',
            field=models.CharField(help_text='Create a test for your kata question', max_length=5000),
        ),
    ]
